version: "3.7"

services:
  web:
    build: .
    networks:
      - nginx-web
    restart: always
    volumes:
      - ./site:/usr/share/nginx/html
  lb:
    image: dockercloud/haproxy
    links:
      - web
    ports:
      - '80:80'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - nginx-web

networks:
  nginx-web:
    driver: bridge
