version: "2.4"

services:
  web:
    build: .
    networks:
      - nginx-web
    restart: always
    hostname: nginx
    volumes:
      - ./src:/var/www/html
      - /var/run/docker.sock:/var/run/docker.sock
    mem_limit: 50m
    mem_reservation: 25m
  lb:
    image: dockercloud/haproxy
    links:
      - web
    ports:
      - '80:80'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - nginx-web
    mem_limit: 50m
    mem_reservation: 25m

networks:
  nginx-web:
    driver: bridge
